"""Bundle the repo into ONE self-contained Kaggle script kernel, then push/poll/fetch it.

    python kaggle/build_kernel.py build  --sweep configs/sweep_probe.json
    python kaggle/build_kernel.py push
    python kaggle/build_kernel.py status
    python kaggle/build_kernel.py output            # -> kaggle/output/

Kaggle "script" kernels are a single file, but Kavi is a package. So build() zips kavi/,
scripts/ and configs/, base64-encodes the zip into the kernel source, and the kernel
unpacks it at runtime. The kernel then (1) installs CuPy if missing, (2) downloads and
tokenises Shakespeare, (3) proves CPU/GPU parity, (4) runs the sweep with --backend cupy.
Results land in /kaggle/working/runs (the kernel's downloadable output).

Notes from earlier Kaggle work on this machine (Brain: transformer-repro, unet-breath-*):
API-pushed GPU kernels get a P100 (sm_60); the kaggle API only works from the Windows
Store Python; kernels_output can choke writing the .log on cp1252 -> set PYTHONUTF8=1.
"""
import argparse
import base64
import io
import json
import os
import shutil
import sys
import time
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "kaggle" / "build"
OUTPUT = ROOT / "kaggle" / "output"
KERNEL_ID = "smirkxd/kavi-gpt"

TEMPLATE = r'''
# Auto-generated by kaggle/build_kernel.py — do not edit; edit the repo and rebuild.
import base64, io, os, subprocess, sys, time, zipfile

BUNDLE = "{bundle}"
SWEEP = "{sweep}"
WORK = "/tmp/kavi-gpt"
OUT = "/kaggle/working/runs"

def sh(*cmd, check=True):
    print("$", " ".join(cmd), flush=True)
    return subprocess.run(cmd, check=check, cwd=WORK)

t0 = time.time()
os.makedirs(WORK, exist_ok=True)
zipfile.ZipFile(io.BytesIO(base64.b64decode(BUNDLE))).extractall(WORK)
subprocess.run(["nvidia-smi"], check=False)
try:
    import cupy
except ImportError:
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "cupy-cuda12x"], check=True)
    import cupy
print("cupy", cupy.__version__, "| device:", cupy.cuda.runtime.getDeviceProperties(0)["name"])

sh(sys.executable, "scripts/prepare_data.py")
sh(sys.executable, "scripts/tokenize_data.py", "char")
sh(sys.executable, "scripts/tokenize_data.py", "bpe", "--vocab", "4096")
sh(sys.executable, "scripts/backend_parity.py")
res = sh(sys.executable, "scripts/sweep.py", SWEEP, "--backend", "cupy", "--out", OUT, check=False)
sh(sys.executable, "scripts/summarize.py", OUT, "--plot", OUT + "/curves.png", check=False)
# keep downloads small: best.npz is enough to sample/resume-from-best; drop last.npz
for d in os.listdir(OUT):
    p = os.path.join(OUT, d, "last.npz")
    if os.path.exists(p):
        os.remove(p)
print(f"total {{(time.time() - t0) / 60:.1f}} min, sweep exit code {{res.returncode}}")
'''


def build(sweep):
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for folder in ("kavi", "scripts", "configs"):
            for f in (ROOT / folder).rglob("*"):
                if f.is_file() and "__pycache__" not in f.parts:
                    z.write(f, f.relative_to(ROOT).as_posix())
    bundle = base64.b64encode(buf.getvalue()).decode()
    if BUILD.exists():
        shutil.rmtree(BUILD)
    BUILD.mkdir(parents=True)
    (BUILD / "kavi_kernel.py").write_text(TEMPLATE.format(bundle=bundle, sweep=sweep),
                                          encoding="utf-8")
    meta = {"id": KERNEL_ID, "title": "kavi-gpt", "code_file": "kavi_kernel.py",
            "language": "python", "kernel_type": "script", "is_private": True,
            "enable_gpu": True, "enable_tpu": False, "enable_internet": True,
            "dataset_sources": [], "competition_sources": [], "kernel_sources": [],
            "model_sources": []}
    (BUILD / "kernel-metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print(f"built kernel ({len(bundle) / 1024:.0f} KB bundle) for sweep {sweep} -> {BUILD}")


def api():
    from kaggle.api.kaggle_api_extended import KaggleApi
    a = KaggleApi()
    a.authenticate()
    return a


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=["build", "push", "status", "output"])
    ap.add_argument("--sweep", default="configs/sweep_probe.json")
    args = ap.parse_args()
    if args.action == "build":
        build(args.sweep)
    elif args.action == "push":
        print(api().kernels_push(str(BUILD)))
    elif args.action == "status":
        print(api().kernels_status(KERNEL_ID))
    elif args.action == "output":
        os.environ.setdefault("PYTHONUTF8", "1")
        if OUTPUT.exists():
            shutil.rmtree(OUTPUT)   # kernels_output skips files that already exist locally
        OUTPUT.mkdir(parents=True)
        try:
            api().kernels_output(KERNEL_ID, str(OUTPUT))
        except Exception as e:      # the .log write can fail on cp1252; data files still land
            print("kernels_output raised (often harmless):", e)
        print(f"downloaded to {OUTPUT}")


if __name__ == "__main__":
    sys.exit(main())
